export const SidebarDataAdmin = [
  {
    tittle: "Tổng quan",
    hasSubRoute: true,
    icon: "layout-grid",
    showSubRoute: false,
    subRoutes: [
      {
        tittle: "Thống kê cửa hàng",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/admin-dashboard",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Hàng hoá",
    hasSubRoute: true,
    icon: "brand-unity",
    showSubRoute: false,
    activeRoute: "product",
    subRoutes: [
      {
        tittle: "Sản phẩm",
        hasSubRoute: false,
        showSubRoute: true,
        route: "/products",
        subRoutes: [],
      },
      {
        tittle: "Giá sản phẩm",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/product-prices",
        subRoutes: [],
      },
      {
        tittle: "Tồn kho",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/inventories",
        subRoutes: [],
      },
      {
        tittle: "Danh mục",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/categories",
        subRoutes: [],
      },
      {
        tittle: "Danh mục con",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/sub-categories",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Giao dịch",
    hasSubRoute: true,
    icon: "layout-grid",
    showSubRoute: false,
    activeRoute: "sales",
    subRoutes: [
      {
        tittle: "Đơn nhập hàng",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/purchase-orders",
        subRoutes: [],
      },
      {
        tittle: "Đơn hoàn hàng",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/return-orders",
        subRoutes: [],
      },
      {
        tittle: "Lịch sử đơn hàng",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/order-history",
        subRoutes: [],
      },
      {
        tittle: "Lịch sử giao dịch",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/transaction-history",
        subRoutes: [],
      },
      {
        tittle: "Khuyến mãi",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/promotions",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Đối tác",
    hasSubRoute: true,
    icon: "users",
    showSubRoute: false,
    activeRoute: "partners",
    subRoutes: [
      {
        tittle: "Khách hàng",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/customers",
        subRoutes: [],
      },
      {
        tittle: "Nhà cung cấp",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/suppliers",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Báo cáo",
    hasSubRoute: true,
    icon: "chart-bar",
    showSubRoute: false,
    activeRoute: "reports",
    subRoutes: [
      {
        tittle: "Doanh thu",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/revenue-report",
        subRoutes: [],
      },
      {
        tittle: "Sản phẩm",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/product-report",
        subRoutes: [],
      },
      {
        tittle: "Khách hàng",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/customer-report",
        subRoutes: [],
      },
      {
        tittle: "Nhà cung cấp",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/supplier-report",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Khác",
    hasSubRoute: true,
    icon: "circle-plus",
    showSubRoute: false,
    activeRoute: "More",
    subRoutes: [
      {
        tittle: "Danh sách tài khoản",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/accounts",
        subRoutes: [],
      },
      {
        tittle: "Vai trò",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/roles-permissions",
        subRoutes: [],
      },
    ],
  },
];
