const defaultUserImg = "src/assets/img/users/default-user.jpg";

export const userlisadata = [
  {
    id: 1,
    img: defaultUserImg,
    username: "Thomas",
    phone: "+12163547758",
    email: "thomas@example.com",
    role: "Admin",
    createdon: "19 Jan 2023",
    status: "Inactive",
  },
  {
    id: 2,
    img: defaultUserImg,
    username: "Rose",
    phone: "+11367529510",
    email: "rose@example.com",
    role: "Manager",
    createdon: "23 Jan 2023",
    status: "Active",
  },
  {
    id: 3,
    img: defaultUserImg,
    username: "Benjamin",
    phone: "+15362789414",
    email: "benjamin@example.com",
    role: "Salesman",
    createdon: "07 Feb 2023",
    status: "Active",
  },
  {
    id: 4,
    img: defaultUserImg,
    username: "Kaitlin",
    phone: "+18513094627",
    email: "kaitlin@example.com",
    role: "Supervisor",
    createdon: "18 Feb 2023",
    status: "Active",
  },
  {
    id: 5,
    img: defaultUserImg,
    username: "Lilly",
    phone: "+14678219025",
    email: "lilly@example.com",
    role: "Store Keeper",
    createdon: "16 Mar 2023",
    status: "Inactive",
  },
  {
    id: 6,
    img: defaultUserImg,
    username: "Freda",
    phone: "+10913278319",
    email: "freda@example.com",
    role: "Purchase",
    createdon: "29 Mar 2023",
    status: "Inactive",
  },
  {
    id: 7,
    img: defaultUserImg,
    username: "Alwin",
    phone: "+19125852947",
    email: "alwin@example.com",
    role: "Delivery Biker",
    createdon: "03 Apr 2023",
    status: "Active",
  },
  {
    id: 8,
    img: defaultUserImg,
    username: "Maybelle",
    phone: "+13671835209",
    email: "maybelle@example.com",
    role: "Maintenance",
    createdon: "13 Apr 2023",
    status: "Active",
  },
  {
    id: 9,
    img: defaultUserImg,
    username: "Ellen",
    phone: "+19756194733",
    email: "ellen@example.com",
    role: "Quality Analyst",
    createdon: "17 May 2023",
    status: "Active",
  },
  {
    id: 10,
    img: defaultUserImg,
    username: "Grace",
    phone: "+19167850925",
    email: "grace@example.com",
    role: "Accountant",
    createdon: "21 May 2023",
    status: "Active",
  },
];