export const all_routes = {
  dashboard: "/",
  users: "/usermanagement/users",
  rolesPermissions: "/usermanagement/roles-permissions",
  products: "/products",
  orders: "/orders",
  settings: "/settings",
  formhorizontal: "/form-horizontal",
  Horizontal: "/layout-horizontal",
  
  superadmindashboard: "/dashboard",

  //  Product routes
  productlist: "/product-list",
  addproduct: "/add-product",
  editproduct: "/product-list/edit",      
  viewproduct: "/product-list/view",      

  expiredproduct: "/expired-products",
  lowstock: "/low-stocks",
  categorylist: "/category-list",
  subcategories: "/sub-categories",
  salesdashboard: "/sales-dashboard",
  saleslist: "/sales-list",
  purchaselist: "/purchase-list",
  companies: "/companies",
  subscription: "/subscription",
  packagelist: "/packages",
  domain: "/domain",
  purchasetransaction: "/purchase-transaction",
  chat: "/chat",
  email: "/email",
  generalsettings: "/general-settings",
  activities: "/activities",
};
